version: '3'

services:
  mysql:
    container_name: salariesnba-mysql
    image: mysql:8
    ports:
    - "3360:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]